# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51cb0c9d8b56560c7f3b8595d295ef58915a55acfc592de45e89277624192f2daad83573cdfadd8c99ebca0e48e2f28e65f929e7c0de8bf3383832a096fcd4a7

test:
  secret_key_base: 4854bce15bea62393c15c4a9a73597168efbd58bcf2b9e493f946942677d78fa8c489b1b274bd00fed9511a5f4c72202e72682e13e33d6ccb0e1681503132ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
